/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as RankingTierListIndexRouteImport } from './routes/ranking/tier-list/index'
import { Route as RankingProfileIndexRouteImport } from './routes/ranking/profile/index'
import { Route as RankingNumberedListIndexRouteImport } from './routes/ranking/numbered-list/index'
import { Route as RankingTierListIdRouteImport } from './routes/ranking/tier-list/$id'
import { Route as RankingNumberedListListIdRouteImport } from './routes/ranking/numbered-list/$listId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingTierListIndexRoute = RankingTierListIndexRouteImport.update({
  id: '/ranking/tier-list/',
  path: '/ranking/tier-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingProfileIndexRoute = RankingProfileIndexRouteImport.update({
  id: '/ranking/profile/',
  path: '/ranking/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingNumberedListIndexRoute =
  RankingNumberedListIndexRouteImport.update({
    id: '/ranking/numbered-list/',
    path: '/ranking/numbered-list/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingTierListIdRoute = RankingTierListIdRouteImport.update({
  id: '/ranking/tier-list/$id',
  path: '/ranking/tier-list/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingNumberedListListIdRoute =
  RankingNumberedListListIdRouteImport.update({
    id: '/ranking/numbered-list/$listId',
    path: '/ranking/numbered-list/$listId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/ranking/numbered-list/$listId': typeof RankingNumberedListListIdRoute
  '/ranking/tier-list/$id': typeof RankingTierListIdRoute
  '/ranking/numbered-list': typeof RankingNumberedListIndexRoute
  '/ranking/profile': typeof RankingProfileIndexRoute
  '/ranking/tier-list': typeof RankingTierListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/ranking/numbered-list/$listId': typeof RankingNumberedListListIdRoute
  '/ranking/tier-list/$id': typeof RankingTierListIdRoute
  '/ranking/numbered-list': typeof RankingNumberedListIndexRoute
  '/ranking/profile': typeof RankingProfileIndexRoute
  '/ranking/tier-list': typeof RankingTierListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/ranking/numbered-list/$listId': typeof RankingNumberedListListIdRoute
  '/ranking/tier-list/$id': typeof RankingTierListIdRoute
  '/ranking/numbered-list/': typeof RankingNumberedListIndexRoute
  '/ranking/profile/': typeof RankingProfileIndexRoute
  '/ranking/tier-list/': typeof RankingTierListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/ranking/numbered-list/$listId'
    | '/ranking/tier-list/$id'
    | '/ranking/numbered-list'
    | '/ranking/profile'
    | '/ranking/tier-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/ranking/numbered-list/$listId'
    | '/ranking/tier-list/$id'
    | '/ranking/numbered-list'
    | '/ranking/profile'
    | '/ranking/tier-list'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/ranking/numbered-list/$listId'
    | '/ranking/tier-list/$id'
    | '/ranking/numbered-list/'
    | '/ranking/profile/'
    | '/ranking/tier-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  RankingNumberedListListIdRoute: typeof RankingNumberedListListIdRoute
  RankingTierListIdRoute: typeof RankingTierListIdRoute
  RankingNumberedListIndexRoute: typeof RankingNumberedListIndexRoute
  RankingProfileIndexRoute: typeof RankingProfileIndexRoute
  RankingTierListIndexRoute: typeof RankingTierListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/tier-list/': {
      id: '/ranking/tier-list/'
      path: '/ranking/tier-list'
      fullPath: '/ranking/tier-list'
      preLoaderRoute: typeof RankingTierListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/profile/': {
      id: '/ranking/profile/'
      path: '/ranking/profile'
      fullPath: '/ranking/profile'
      preLoaderRoute: typeof RankingProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/numbered-list/': {
      id: '/ranking/numbered-list/'
      path: '/ranking/numbered-list'
      fullPath: '/ranking/numbered-list'
      preLoaderRoute: typeof RankingNumberedListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/tier-list/$id': {
      id: '/ranking/tier-list/$id'
      path: '/ranking/tier-list/$id'
      fullPath: '/ranking/tier-list/$id'
      preLoaderRoute: typeof RankingTierListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/numbered-list/$listId': {
      id: '/ranking/numbered-list/$listId'
      path: '/ranking/numbered-list/$listId'
      fullPath: '/ranking/numbered-list/$listId'
      preLoaderRoute: typeof RankingNumberedListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  RankingNumberedListListIdRoute: RankingNumberedListListIdRoute,
  RankingTierListIdRoute: RankingTierListIdRoute,
  RankingNumberedListIndexRoute: RankingNumberedListIndexRoute,
  RankingProfileIndexRoute: RankingProfileIndexRoute,
  RankingTierListIndexRoute: RankingTierListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
